#!/bin/sh
set -e

case "$1" in
    remove | purge)
        if [ -d /run/systemd/system ]; then systemctl daemon-reload || true; fi
        ;;
esac

if [ "$1" = purge ]; then
    rm -rf /etc/rtspwall /var/lib/rtspwall
    if getent passwd rtspwall >/dev/null; then deluser --system --quiet rtspwall || true; fi
    if getent group rtspwall >/dev/null; then delgroup --system --quiet rtspwall || true; fi
fi

exit 0
