#!/bin/sh
set -e

case "$1" in
    remove | purge)
        if [ -d /run/systemd/system ]; then systemctl daemon-reload || true; fi
        ;;
esac

if [ "$1" = purge ]; then
    rm -rf /etc/rpi4-rtsp
    if getent passwd rpi4-rtsp >/dev/null; then deluser --system --quiet rpi4-rtsp || true; fi
    if getent group rpi4-rtsp >/dev/null; then delgroup --system --quiet rpi4-rtsp || true; fi
fi

exit 0
