#!/bin/sh
set -e

case "$1" in
    remove | deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl disable --now rtspwall-config.path >/dev/null 2>&1 || true
            systemctl stop rtspwall-config.service rtspwall-demo.service || true
            systemctl stop rtspwall.service || true
            systemctl disable rtspwall.service >/dev/null 2>&1 || true
        fi
        ;;
    upgrade | failed-upgrade) ;; # postinst does try-restart
    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
