#!/bin/sh
# make-clips.sh — generates the rtspwall demo clips (cam1.mp4 .. cam5.mp4).
#
# Usage: sh demo/make-clips.sh [OUTDIR]     (default: the directory of this script)
#
# The clips are synthetic (ffmpeg testsrc2 plus text) and dedicated to the
# public domain under CC0 1.0: https://creativecommons.org/publicdomain/zero/1.0/
#
# Fixed format, chosen so the demo runs on a stock Pi 4 (about 22 % of the
# H.264 decoder budget for all five, default gpu_mem) and loops cleanly:
#   640x360, 25 fps, H.264 Main, no B-frames (-bf 0), 1 s GOP with an IDR on
#   the first frame, 10 s, MP4 with the index up front (+faststart; the
#   daemon seeks back to the start on EOF), no audio, <= 1 MB each.
set -eu

out=${1:-$(dirname "$0")}
command -v ffmpeg >/dev/null 2>&1 || {
	echo "make-clips.sh: ffmpeg not found (sudo apt install ffmpeg)" >&2
	exit 1
}
mkdir -p "$out"

# Font for drawtext: fontconfig's default sans when available, else the
# DejaVu file directly (Debian: fonts-dejavu-core).
font="font=Sans"
for f in /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf \
	 /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf; do
	if [ -f "$f" ]; then
		font="fontfile=$f"
		break
	fi
done

n=1
while [ "$n" -le 5 ]; do
	hue=$(( (n - 1) * 72 ))
	tmp="$out/.cam$n.tmp.mp4"
	ffmpeg -nostdin -hide_banner -loglevel error -y \
		-f lavfi -i "testsrc2=size=640x360:rate=25:duration=10" \
		-vf "hue=h=$hue,drawbox=x=0:y=0:w=iw:h=56:color=black@0.6:t=fill,drawtext=$font:text='CAM $n':x=16:y=12:fontsize=32:fontcolor=white,drawtext=$font:text='%{pts\\:hms}':x=w-tw-16:y=12:fontsize=32:fontcolor=white" \
		-an -c:v libx264 -profile:v main -level:v 3.0 -pix_fmt yuv420p \
		-bf 0 -g 25 -keyint_min 25 -sc_threshold 0 -forced-idr 1 \
		-crf 30 -maxrate 600k -bufsize 1200k \
		-metadata title="rtspwall demo CAM $n" \
		-metadata copyright="CC0 1.0 (public domain), generated by rtspwall demo/make-clips.sh" \
		-movflags +faststart "$tmp"
	n=$((n + 1))
done
# All five or none: rename into place only after every clip was written.
n=1
while [ "$n" -le 5 ]; do
	mv "$out/.cam$n.tmp.mp4" "$out/cam$n.mp4"
	n=$((n + 1))
done
ls -l "$out"/cam[1-5].mp4
